CimKara/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Ensachage.urls')),
    path('', include('Users.urls')),
]

Ensachage/urls.py
from django.urls import path
from .views import *
from django.http import HttpResponse
from django.contrib.auth.models import User



app_name = 'data'
urlpatterns = [
    path('', index_views, name="index_name"),
    path('detail/', detail_views, name="detail_name"),
    path('filter_by_year/', filter_views, name="filter_name"),
    path('yesterday/', yesterday_views, name="yesterday_name"),
    path('day/', day_views, name="day_name"),
    path('month/', month_views, name="month_name"),
    path('add_form/', add_form_views, name='add_form_name'),
    path('update/', update_form_views, name="update_name"),
]

Users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views


app_name = 'users'

urlpatterns = [
    path('login/', login_views, name="logIn"),
    path('logup/', logup_views, name='logup'),
    path('logout/', logout_views, name='logOut'),
    # path('logup/userCreate/', logup_user_create_views, name="createUser"),
    
    path('reset_password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', views.PasswordResetDoneView.as_view(), name='reset_password_send'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='reset_password_confirm'),
    path('reset_password_complete/', views.PasswordResetCompleteView.as_view(), name='reset_password_complete'),
    
]

templates/Production/add_form.html
{% extends 'home.html' %}

{% block title %}Add Form{% endblock title %}

{% block content %}
<div class="container">

  <div class="card text-center bg-dark">
    <div class="card-header">
      <!-- {% include 'Production/menu.html' %} -->
      <h5 class=" h2 text-uppercase text-light">formulaire de saisie</h5>
      <!-- <p class="text-light">Daily statistics of all posts</p> -->
    </div>

    <div class="container-fluid">
      <section class="pb-5">

        <div class="row">
          <div class="col-lg-4 col-sm-12 clo-md-4 mt-4"></div>
          <div class="col-lg-4 col-sm-12 clo-md-4 mt-4">
            <div class="card" style="background-color: #000000;">
              <div class="h4 card-header text-capitalize">
                <div class="row">
                  <div class="col-12 mt-3 mb-1">
                    <h5 class=" h4 text-uppercase text-light">register form</h5>
                  </div>
                </div>

              </div>
              <div class="card-body mt-2">
                <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                  <!-- 2 column grid layout with text inputs for the first and last names -->
                  <div class="row mb-4">
                    <div class="col">
                      <div data-mdb-input-init class="form-outline">
                        <input readonly type="text" id="form3Example1" class="form-control" name="username"
                          value="{{ user.username }}" required />
                        <label class="form-label" for="form3Example1">Username</label>
                      </div>
                    </div>
                    <div class="col">
                      <div data-mdb-input-init class="form-outline">
                        <input type="number" id="form3Example2" class="form-control text-light" name="livraison" value="0"
                          required />
                        <label class="form-label text-light" for="form3Example2">Livraison</label>
                      </div>
                    </div>
                  </div>
                  <div class="row mb-4">
                    <div class="col">
                      <div data-mdb-input-init class="form-outline">
                        <input type="number" id="form3Example1" class="form-control text-light" name="casse" value="0" required />
                        <label class="form-label text-light" for="form3Example1">Casse</label>
                      </div>
                    </div>
                    <div class="col">
                      <div data-mdb-input-init class="form-outline">
                        <input type="text" id="form3Example2" class="form-control text-light" name="vrac" value="0.0" required />
                        <label class="form-label text-light" for="form3Example2">Vrac</label>
                      </div>
                    </div>
                  </div>
                  <!-- Password input -->
                  <div data-mdb-input-init class="form-outline mb-4">
                    <input type="date" id="form3Example4" class="form-control text-light" name="date" required />
                    <label class="form-label text-light" for="form3Example4">Date</label>
                  </div>
                  <!-- Submit button -->
                  <button data-mdb-ripple-init type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
                </form>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-sm-12 clo-md-4 mt-4"></div>
        </div>

      </section>
    </div>
  </div>
</div>
{% endblock content %}

templates/Production/day.html
{% extends 'home.html' %}

{% block title %}Day{% endblock title %}
{% block content %}
<div class="container">

    <div class="card text-center bg-dark">
        <div class="card-header">
            <!-- {% include 'Production/menu.html' %} -->
            <div class="col-12 mt-3 mb-1">
                <h5 class=" h2 text-uppercase text-light">daily bagging statistics</h5>
                <p class="text-light">Daily statistics of all posts</p>
            </div>
        </div>

        <!-- <hr> -->

        <div class="container-fluid">
            <section>
                <div class="row mt-3">
                    <div class="col-xl-6 col-md-12 mb-4">
                        <div class="card text-light">
                            <div class="card-body" style="background-color: #000000">
                                <div class="d-flex justify-content-between p-md-1">
                                    <div class="d-flex flex-row">
                                        <div class="align-self-center">
                                            <i class="fab fa-battle-net text-info fa-3x me-4"></i>
                                        </div>
                                        <div>
                                            <h4>Total Delivery</h4>
                                            <p class="mb-0">Monthly delivery</p>
                                        </div>
                                    </div>
                                    <div class="align-self-center">
                                        {% if liv_total.liv %}<h2 class="h1 mb-0">{{ liv_total.liv }}</h2>{% else %}
                                        <h2 class="h1 mb-0">0</h2>{% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-md-12 mb-4">
                        <div class="card text-light">
                            <div class="card-body" style="background-color: #000000">
                                <div class="d-flex justify-content-between p-md-1">
                                    <div class="d-flex flex-row">
                                        <div class="align-self-center">
                                            <i class="fab fa-battle-net text-info fa-3x me-4"></i>
                                        </div>
                                        <div>
                                            <h4>Total broken</h4>
                                            <p class="mb-0">Monthly breakage</p>
                                        </div>
                                    </div>
                                    <div class="align-self-center">
                                        {% if cas_total.cas %}<h2 class="h1 mb-0">{{ cas_total.cas }}</h2>{% else %}
                                        <h2 class="h1 mb-0">0.0</h2>{% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xl-6 col-md-12 mb-4">
                        <div class="card text-light">
                            <div class="card-body" style="background-color: #000000">
                                <div class="d-flex justify-content-between p-md-1">
                                    <div class="d-flex flex-row">
                                        <div class="align-self-center">
                                            <i class="fab fa-battle-net text-info fa-3x me-4"></i>
                                        </div>
                                        <div>
                                            <h4>Total Bagged</h4>
                                            <p class="mb-0">Monthly bagged</p>
                                        </div>
                                    </div>
                                    <div class="align-self-center">
                                        {% if ens_total.ens %}<h2 class="h1 mb-0">{{ ens_total.ens }}</h2>{% else %}
                                        <h2 class="h1 mb-0">0</h2>{% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-md-12 mb-4">
                        <div class="card text-light">
                            <div class="card-body" style="background-color: #000000">
                                <div class="d-flex justify-content-between p-md-1">
                                    <div class="d-flex flex-row">
                                        <div class="align-self-center">
                                            <i class="fab fa-battle-net text-info fa-3x me-4"></i>
                                        </div>
                                        <div>
                                            <h4>Total Breakage Rate</h4>
                                            <p class="mb-0">Monthly Breakage Rate</p>
                                        </div>
                                    </div>
                                    <div class="align-self-center">
                                        {% if tx_cas_total.tx_cas %}<h2 class="h1 mb-0">{{ tx_cas_total.tx_cas|floatformat:2 }}</h2>{% else %}
                                        <h2 class="h1 mb-0">0.0</h2>{% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {% if vra_total.vra %}
                <div class="row">
                    <div class="col-xl-6 col-md-12 mb-4">
                        <div class="card text-light">
                            <div class="card-body" style="background-color: #000000">
                                <div class="d-flex justify-content-between p-md-1">
                                    <div class="d-flex flex-row">
                                        <div class="align-self-center">
                                            <i class="fab fa-battle-net text-info fa-3x me-4"></i>
                                        </div>
                                        <div>
                                            <h4>Total Bulk Delivery</h4>
                                            <p class="mb-0">Monthly Bulk Delivery</p>
                                        </div>
                                    </div>
                                    <div class="align-self-center">
                                        {% if vra_total.vra %}<h2 class="h1 mb-0">{{ vra_total.vra }}</h2>{% else %}
                                        <h2 class="h1 mb-0"></h2>{% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                {% endif %}

        </div>

        </section>
    </div>
</div>

{% endblock %}

templates/Production/detail.html
{% extends 'home.html' %}

{% block title %}Detail{% endblock title %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div style="font-family: 'Playfair Display', serif;">
            <div class="card bg-dark">
                <div class="card-header bg-info bg-gradient mb-0 text-center">
                    <h1 class="fs-3 text-light text-uppercase"><i class="fas fa-rectangle-list me-1"></i>tableau
                        récaptulatif</h1>
                </div>

                <div class="d-flex justify-content-between align-items-center mt-4 mx-5">
                    <form class="row gy-2 gx-3 align-items-center">
                        <div class="col-auto">
                            <div data-mdb-input-init class="form-outline">
                                <input type="text" id="form11Example1" class="form-control text-dark"
                                    name="username" value="{{ user.username }}" required readonly />
                                <label class="form-label text-light" for="form11Example1">Username:</label>
                            </div>
                        </div>
                        <div class="col-auto">
                            <div data-mdb-input-init class="form-outline">
                                <input type="text" id="form11Example1" class="form-control text-light" name="month"  
                                    {% if month %}
                                        value="{{ month }}"
                                    {% else %}
                                        value=""
                                    {% endif %} required />
                                <label class="form-label text-light" for="form11Example1">Mois:</label>
                            </div>
                        </div>

                        <div class="col-auto">
                            <div data-mdb-input-init class="form-outline">
                                <input type="text" id="form11Example1" class="form-control text-light" name="year"
                                {% if year %}
                                    value="{{ year }}"
                                {% else %}
                                    value=""
                                {% endif %} required />
                                <label class="form-label text-light" for="form11Example1">Année:</label>
                            </div>
                        </div>
                        <div class="col-auto">
                            <button data-mdb-ripple-init type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                    <div class=" col-auto ms-5"><a class="text-decoration-none fst-italic fs-5"
                        href="/filter_by_year/?username={{ user.username}}"><i class="fas fa-circle-chevron-right fa-2x ms-2"></i></a></div>
                </div>

                <div class="card-body">
                    <!-- <div class="container-fluid"> -->
                        
                    <!-- </div> -->


                    <div class="table-responsive">
                        <table class="table table-striped table-dark">
                            <thead>
                                <tr class="table-primary">
                                    <th class="fs-3 text-center text-dark mb-0">Date</th>
                                    <th class="fs-3 text-center text-dark mb-0">Livraison</th>
                                    <th class="fs-3 text-center text-dark mb-0">Casse</th>
                                    <th class="fs-3 text-center text-dark mb-0">Ensaches</th>
                                    <th class="fs-3 text-center text-dark mb-0">Taux_Casse</th>
                                    <th class="fs-3 text-center text-dark mb-0">Vrac</th>
                                    <th class="fs-3 text-center text-dark mb-0">Action</th>
                                </tr>
                            </thead>
                            <tbody class="">
                                {% for post in posts %}
                                <tr class="">
                                    {% if post.created %}<td class="text-center fs-5">{{ post.created|date:'d/n/o' }}</td>{% else %}<td class="text-center"></td>{% endif %}
                                    {% if post.livraison %}<td class="text-center fs-5">{{ post.livraison }}</td>{% else %}<td class="text-center"></td>{% endif %}
                                    {% if post.casse %}<td class="text-center fs-5">{{ post.casse }}</td>{% else %}<td class="text-center"></td>{% endif %}
                                    {% if post.ensache %}<td class="text-center fs-5">{{ post.ensache }}</td>{% else %}<td class="text-center"></td>{% endif %}
                                    {% if post.tx_casse %}<td class="text-center fs-5">{{ post.tx_casse|floatformat:2 }}</td>{% else %}<td class="text-center"></td>{% endif %}
                                    {% if post.vrac %}<td class="text-center fs-5">{{ post.vrac|floatformat:2 }}</td>
                                    {%else %}<td class="text-center"></td>{% endif %}
                                    <td class="text-center"><a class="btn btn-warning"href="/update/?id_post={{ post.id }}"><i class="fas fa-feather-pointed me-1"></i>Edit</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card-footer table-responsive">
                    <div class="table-responsive">
                        <table class="table table-striped table-dark">
                            <tfoot>
                                <tr class="table-primary">
                                    <th class="fs-3 text-center text-dark mb-0">Total:</th>
                                    <th class="fs-3 text-center text-dark mb-0">{{ liv_total.liv }}</th>
                                    <th class="fs-3 text-center text-dark mb-0">{{ cas_total.cas }}</th>
                                    <th class="fs-3 text-center text-dark mb-0">{{ ens_total.ens }}</th>
                                    <th class="fs-3 text-center text-dark mb-0">{{ tx_cas_total.tx_cas|floatformat:2 }}
                                    </th>
                                    <th class="fs-3 text-center text-dark mb-0">{{ vra_total.vra|floatformat:2 }}</th>
                                    <th class="fs-3 text-center text-dark mb-0"></th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock content %}

templates/Production/edit.html
{% extends "home.html" %}

{% block title %}Edité{% endblock title %}

{% block content %}
    <div class="container">
        <div class="col-12">
            <div class="card">
              <div class="card">
                <div
                  class="card-header bg-info bg-gradient fs-3 text-center text-white text-uppercase fw-bold"><i class="fas fa-rectangle-list me-1"></i>formulaire
                </div>
                <div class="card-body">
                  <blockquote class="blockquote mb-0">
                    <div class="mb-sm-0">
                      <form action="" method="post">
                        {% csrf_token %} {{ form.as_p }}
                        <div class="d-grid gap">
                          <button type="submit" class="btn btn-primary">
                            SUBMIT
                          </button>
                        </div>
                      </form>
                    </div>
                  </blockquote>
                </div>
              </div>
            </div>
          </div>
    </div>
{% endblock content %}
    

templates/Production/filter.html
{% extends 'home.html' %}

{% block title %}By year{% endblock title %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div style="font-family: 'Playfair Display', serif;">
            <div class="card bg-dark">
                <div class="card-header bg-info bg-gradient mb-0 text-center">
                    <h1 class="fs-3 text-light text-uppercase"><i class="fas fa-rectangle-list me-1"></i>tableau
                        récaptulatif</h1>
                </div>

                <div class="d-flex justify-content-between align-items-center mt-4 mx-5">
                    <form class="row gy-2 gx-3 align-items-center">
                        <div class="col-auto">
                            <div data-mdb-input-init class="form-outline">
                                <input type="text" id="form11Example1" class="form-control text-dark"
                                    name="username" value="{{ user.username }}" required readonly />
                                <label class="form-label text-light" for="form11Example1">Name:</label>
                            </div>
                        </div>
                        
                        <div class="col-auto">
                            <div data-mdb-input-init class="form-outline">
                                <input type="text" id="form11Example1" class="form-control text-light" name="year"
                                    
                                    {% if year %}
                                        value="{{ year }}"
                                    {% else %}
                                        value=""
                                    {% endif %}
                                         required />
                                <label class="form-label text-light" for="form11Example1">Année:</label>
                            </div>
                        </div>
                        <div class="col-auto">
                            <button data-mdb-ripple-init type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                    <div class=" col-auto ms-5"><a class="text-decoration-none fst-italic fs-5"
                        href="/detail/?username={{ user.username }}"><i class="fas fa-circle-chevron-left fa-2x ms-2"></i></a></div>
                </div>

                <div class="card-body">
                    <!-- <div class="container-fluid"> -->
                        
                    <!-- </div> -->


                    <div class="table-responsive">
                        <table class="table table-striped table-dark">
                            <thead>
                                <tr class="table-primary">
                                    <th class="fs-3 text-center text-dark mb-0">Date</th>
                                    <th class="fs-3 text-center text-dark mb-0">Livraison</th>
                                    <th class="fs-3 text-center text-dark mb-0">Casse</th>
                                    <th class="fs-3 text-center text-dark mb-0">Ensaches</th>
                                    <th class="fs-3 text-center text-dark mb-0">Taux_Casse</th>
                                    <th class="fs-3 text-center text-dark mb-0">Vrac</th>
                                    <th class="fs-3 text-center text-dark mb-0">Action</th>
                                </tr>
                            </thead>
                            <tbody class="">
                                {% for post in posts %}
                                <tr class="">
                                    {% if post.created %}<td class="text-center fs-5">{{ post.created|date:'d/n/o' }}</td>{% else %}<td class="text-center"></td>{% endif %}
                                    {% if post.livraison %}<td class="text-center fs-5">{{ post.livraison }}</td>{% else %}<td class="text-center"></td>{% endif %}
                                    {% if post.casse %}<td class="text-center fs-5">{{ post.casse }}</td>{% else %}<td class="text-center"></td>{% endif %}
                                    {% if post.ensache %}<td class="text-center fs-5">{{ post.ensache }}</td>{% else %}<td class="text-center"></td>{% endif %}
                                    {% if post.tx_casse %}<td class="text-center fs-5">{{ post.tx_casse|floatformat:2 }}</td>{% else %}<td class="text-center"></td>{% endif %}
                                    {% if post.vrac %}<td class="text-center fs-5">{{ post.vrac|floatformat:2 }}</td>
                                    {%else %}<td class="text-center"></td>{% endif %}
                                    <td class="text-center"><a class="btn btn-warning"href="/update/?id_post={{ post.id }}"><i class="fas fa-feather-pointed me-1"></i>Edit</a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card-footer table-responsive">
                    <div class="table-responsive">
                        <table class="table table-striped table-dark">
                            <tfoot>
                                <tr class="table-primary">
                                    <th class="fs-3 text-center text-dark mb-0">Total:</th>
                                    <th class="fs-3 text-center text-dark mb-0">{{ liv_total.liv }}</th>
                                    <th class="fs-3 text-center text-dark mb-0">{{ cas_total.cas }}</th>
                                    <th class="fs-3 text-center text-dark mb-0">{{ ens_total.ens }}</th>
                                    <th class="fs-3 text-center text-dark mb-0">{{ tx_cas_total.tx_cas|floatformat:2 }}
                                    </th>
                                    <th class="fs-3 text-center text-dark mb-0">{{ vra_total.vra|floatformat:2 }}</th>
                                    <th class="fs-3 text-center text-dark mb-0"></th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock content %}

templates/Production/menu.html
<ul class="nav nav-tabs card-header-tabs">
    <li class="nav-item">
        <a class="nav-link text-light" href="{% url 'data:day_name' %}">Day</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-light" href="{% url 'data:yesterday_name' %}">Yesterday</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-light" href="{% url 'data:month_name' %}">Month</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link text-light" href="{% url 'data:add_form_name' %}">Add Form</a>
    </li>
    {% endif %}
</ul>

templates/Production/validate.html
{% extends 'home.html' %}


{% block content %}
<div class="container text-center">
    <h1 class="h4">bienvenus sur la page</h1>
    {% if update %}
    <div class="alert alert-success">
        <p class="h5">Votre modification a été éffectuée avec succes cliqué <a href="/detail/?username={{ user.username }}">Ici</a>
            pour y retourner</p>
    </div>
    {% endif %}
    
    {% if add %}    
        <div class="alert alert-success">
            <p class="h5">Votre ajout de données a été éffectuée avec succes cliqué <a href="/detail/?username={{ user.username }}">Ici</a>
                pour y retourner</p>
        </div> 
    {% endif %}
</div>
{% endblock content %}